name: OWASP ZAP Baseline Scan
on:
  push:
    branches:
     - main
jobs:
  your_job_name:
    runs-on: ubuntu-latest
    steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.4.0
      with:
        target: 'https://juice-shop.herokuapp.com'
    - name: Install dependencies
        run: npm install @octokit/rest